
apiVersion: apps/v1
kind: Deployment
metadata:
  name: food
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food
  template:
    metadata:
      labels:
        app: food
    spec:
      containers:
      - name: cont1
        image: shaikmustafa/cycle
        ports:
          - containerPort: 80
