
apiVersion: apps/v1
kind: Deployment
metadata:
  name: food
spec:
  replicas: 3
  selector:
    matchLabels:
      app: food
  template:
    metadata:
      labels:
        app: food
    spec:
      containers:
      - name: cont1
        image: shaikmustafa/dm
        ports:
          - containerPort: 80
