---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
specs:
  replicas: 3
  selectors:
    app: food
  matchLabels:
    template:
      app: food
    containers:
      - name: cont1
        image: shaikmustafa/dm
        ports:
          - containerPort: 80
